---
# file: roles/ntp_client/tasks/main.yml
- include: installPackages.yml
  tags:
  - aspects_ntp_client
- name: include correct vars file
  include_vars: "roles/aspects_ntp_client/defaults/{{ ansible_os_family }}.yml"
  tags:
    - aspects_ntp_client

- name: Set ntp.conf template
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp
  tags:
    - aspects_ntp_client