---
# file: roles/ntp_client/tasks/main.yml

- name: include correct vars file
  include_vars: "roles/aspects_ntp_client/defaults/{{ ansible_os_family }}.yml"
  tags:
    - ntp

- name: Set ntp.conf template
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp
  tags:
    - ntp